# Generated by Django 5.2.4 on 2025-12-13 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evangelism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=200)),
                ('course', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('faith', models.CharField(choices=[('strong_faith', 'Strong Faith'), ('less_faith', 'Less Faith'), ('unbeliever', 'Unbeliever'), ('unknown', 'Unknown')], max_length=20)),
                ('relevance', models.IntegerField(blank=True)),
                ('completed', models.BooleanField(default=False)),
                ('evangelist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('evangelism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='tracker.evangelism')),
            ],
        ),
        migrations.AddConstraint(
            model_name='evangelism',
            constraint=models.UniqueConstraint(fields=('evangelist', 'person_name'), name='unique_evangelist_person_name', violation_error_message='An Evangelism with this user and person_name already exists.'),
        ),
    ]
